### ISSUE TITLE
Sensorless ERCF

### ISSUE THREAD

**Issue by appleimperio** [sneakytreesnake/StealthOrbiter#11]
This is not an issue is more of a question. I'm planning to use the ERCF sensorless option and my orbiter 2 has the orbiter filament sensor. Can I use like that or I need a bowden coupler (as the manual suggest) instead of the light in the filament sensor?

**Comment by sneakytreesnake** [comment]
I found the bowden tube was quite loose in the clear filament sensor part, and sometimes would pop out.

I ended up removing the orbiter sensor entirely as it was not needed and just caused issues for me.
