### ISSUE TITLE
filament_switch_sensor toolhead_sensor question

### ISSUE THREAD

**Issue by suizhenmin** [sneakytreesnake/StealthOrbiter#2]
Hi orBiter Filament Sensor sensor releases V2.2 version. Now no matter how to set it, the filament state is displayed. How can I make it?

The following is my setting

[filament_switch_sensor toolhead_sensor]            
pause_on_runout: False
#runout_gcode: PAUSE #PAUSE WHEN FILAMENT RUNS OUT - DOES THIS SCREW WITH ERCF?
# filament sensor wired to the ERB or Printer MCU
#switch_pin: ercf:gpio25 #ERB
switch_pin: !PA1 #Printer MCU - FYSETC CHEETAH_MIX
#switch_pin: ^P1.27 #Printer MCU - BTT SKR board

**Comment by sneakytreesnake** [comment]
It should just require inverting the pin in klipper config.

I believe the orbiter sensor page has more instructions on how to set the sensor software up.

**Comment by suizhenmin** [comment]
Does the original OrbiterSensor.cfg configuration need to be disabled?

**Comment by sneakytreesnake** [comment]
Yes disable the original .cfg file, and use the new OrbiterSensorV2.2.cfg file.

**Comment by suizhenmin** [comment]
I almost gave up, now when the _ERCF_CALIBRATE is calibrated, the filament reaches the entrance of the extruder, but the extruder is in the state of returning material, maybe I will find an official Orbiter v2.0 base file to use ercf plan.

**Comment by suizhenmin** [comment]
I checked your STL file, you used a material break detection alone, installed under the extruder base, can you provide the following BOM list?

**Comment by sneakytreesnake** [comment]
I've added a BOM and updated the description to make the installation more clear.
