### ISSUE TITLE
ORBITERMOUNT_BASIC includes the filament sensor

### ISSUE THREAD

**Issue by pringsen** [sneakytreesnake/StealthOrbiter#5]
Wanted to go for the basic orbiter 2.0 mount without the filament sensor as i already have a runout sensor. However the version commited [6ee4ddf](https://github.com/sneakytreesnake/StealthOrbiter/commit/6ee4ddfd58f019e01a67f769358c1449047b22aa) includes the recess for the filament sensor.

https://github.com/sneakytreesnake/StealthOrbiter/blob/6ee4ddfd58f019e01a67f769358c1449047b22aa/STL/ORBITERMOUNT_BASIC_V1.stl

**Comment by sneakytreesnake** [comment]
Not exactly sure how I mixed that up.... fixed now
