### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by marc-gist** [sneakytreesnake/StealthOrbiter#7]
Thank you for sharing! Do you have a link to any install guides/videos... I'm not really sure about how one installs on to the motor the chain guide, etc, or what exactly all the parts are that are needed to be printed between your stl and the linked one.

**Comment by sneakytreesnake** [comment]
Give me a few days and I'll put together an install guide/video 😀

**Comment by sneakytreesnake** [comment]
Hello, I've added a set of diagrams and descriptions. I've kept the links to the other design, as I don't yet have permission to upload them as part of this design.

Let me know how you get on, and if any other info would be useful!

**Comment by sneakytreesnake** [comment]
Closed as install guide has been added, and no further comments made
